# Generated by Django 4.1.7 on 2023-03-10 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'book_format',
                'verbose_name_plural': 'book_formats',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(max_length=150, upload_to='products/images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('full_title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('language', models.CharField(choices=[('uzb/rus', 'Uzb Rus'), ('uzb', 'Uzb'), ('rus', 'Rus'), ('cyr', 'Cyr'), ('eng', 'Eng')], default='uzb', max_length=15)),
                ('volume', models.PositiveIntegerField(default=1)),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('cover', models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft')], default='hard', max_length=15)),
                ('info', models.JSONField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.bookformat')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'ordering': ('full_title',),
            },
        ),
    ]
